/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package lacsessionrecord;

import java.awt.Cursor;
import java.awt.KeyboardFocusManager;
import java.awt.Point;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.util.Collections;
import java.util.Random;
import javax.swing.AbstractButton;

/**
 *
 * @author Del
 */
public class LacSessionRecords extends javax.swing.JFrame {

    private boolean ot = false;
    private boolean sd = false;
    private boolean ind = false;
    private boolean gr = false;
    private boolean ww = false;
    private boolean g = false;
    private boolean noShow = false;
    private boolean ma = false;
    private boolean sc = false;
    private boolean wr = false;
    private boolean rd = false;
    private boolean ss = false;
    private String[] timeIn = {"9:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00"};
    private String[] timeOut = {"10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00"};
    private String resourceCode = "00000";
    private String studentId;
    private String courseNumber;
    private String date;
    private FileWriter fstream;
    private BufferedWriter fbw;

   
    /**
     * Creates new form LacSessionRecords
     */
    public LacSessionRecords() {
        this.setLocation(300, 300);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jCheckBox12 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel1.setText("Student ID");

        jTextField1.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel2.setText("Course #");

        jTextField2.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jCheckBox1.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jCheckBox1.setText("GWAR");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jCheckBox2.setText("Individual");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jCheckBox2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCheckBox2KeyPressed(evt);
            }
        });

        jCheckBox3.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jCheckBox3.setText("Group");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jCheckBox4.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jCheckBox4.setText("OneTime");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        jCheckBox5.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jCheckBox5.setText("SameDay");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });

        jCheckBox6.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jCheckBox6.setText("Math");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });

        jCheckBox7.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jCheckBox7.setText("Science");
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });

        jCheckBox8.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jCheckBox8.setText("Writing");
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });

        jCheckBox9.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jCheckBox9.setText("Reading");
        jCheckBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox9ActionPerformed(evt);
            }
        });

        jCheckBox10.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jCheckBox10.setText("Study Skill");
        jCheckBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox10ActionPerformed(evt);
            }
        });

        jCheckBox11.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jCheckBox11.setText("No Show");
        jCheckBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox11ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jButton1.setText("record");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCheckBox12.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jCheckBox12.setText("WW");
        jCheckBox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox12ActionPerformed(evt);
            }
        });

        jLabel3.setText("Ex:910300526");

        jLabel4.setText("Ex:3/18/12");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel5.setText("Date");

        jTextField3.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel6.setText("Ex: MATH70");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel7.setText("Last Entered");

        jButton2.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(11, 11, 11)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 138, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel3)
                        .add(38, 38, 38)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 86, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel4)
                                .add(44, 44, 44)
                                .add(jTextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 101, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel6)
                                .add(0, 0, Short.MAX_VALUE))
                            .add(layout.createSequentialGroup()
                                .add(jLabel5)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jLabel2)
                                .add(190, 190, 190))))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jCheckBox1)
                            .add(jCheckBox6))
                        .add(53, 53, 53)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jCheckBox2)
                            .add(jCheckBox7))
                        .add(59, 59, 59)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jCheckBox3)
                            .add(jCheckBox8))
                        .add(63, 63, 63)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jCheckBox9)
                            .add(jCheckBox4))
                        .add(53, 53, 53)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jCheckBox5)
                            .add(jCheckBox10))
                        .add(58, 58, 58)))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jCheckBox11)
                    .add(jCheckBox12)
                    .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 97, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .add(14, 14, 14)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(jButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 841, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jLabel7))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel1)
                            .add(jLabel2)
                            .add(jLabel5))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE, false)
                            .add(jTextField1)
                            .add(jTextField2)
                            .add(jLabel3)
                            .add(jLabel4)
                            .add(jTextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel6)))
                    .add(layout.createSequentialGroup()
                        .add(31, 31, 31)
                        .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(33, 33, 33)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jCheckBox1)
                    .add(jCheckBox2)
                    .add(jCheckBox3)
                    .add(jCheckBox4)
                    .add(jCheckBox5)
                    .add(jCheckBox12))
                .add(21, 21, 21)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jCheckBox6)
                    .add(jCheckBox7)
                    .add(jCheckBox8)
                    .add(jCheckBox9)
                    .add(jCheckBox10)
                    .add(jCheckBox11))
                .add(49, 49, 49)
                .add(jLabel7)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 67, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed

    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
         char s[] = new char[9];
        String text1 = jTextField1.getText();
        studentId = text1;
        for (int i = 0; i < s.length; i++){
          s[i] = studentId.charAt(i);
        }
        studentId = s[0]+""+s[1]+""+s[2]+"-"+s[3]+""+s[4]+"-"+s[5]+""+s[6]+""+s[7]+""+s[8];
       
        String text2 = jTextField2.getText();
        date = text2;   
        String text3 = jTextField3.getText();
        courseNumber = text3;
        ot = jCheckBox4.isSelected();
        sd = jCheckBox5.isSelected();
        ind = jCheckBox2.isSelected();
        gr = jCheckBox3.isSelected();
        ww = jCheckBox12.isSelected();
        g = jCheckBox1.isSelected();
        noShow = jCheckBox11.isSelected();
        ma = jCheckBox6.isSelected();
        sc = jCheckBox7.isSelected();
        wr = jCheckBox8.isSelected();
        rd = jCheckBox9.isSelected();
        ss = jCheckBox10.isSelected();
        
        Random randomIndex = new Random();
        int indexForTimeInOut = randomIndex.nextInt(7);

         try{

            fstream = new FileWriter("test",true);
            fbw = new BufferedWriter(fstream);

            if(ss && ind) resourceCode = "00001";
            if(ss && sd) resourceCode = "00002";
            if(ss && gr) resourceCode = "00003";
            if(rd && ind) resourceCode = "00010";
            if(rd && sd) resourceCode = "00020";
            if(rd && gr) resourceCode = "00030";
            if(rd && ss && ind) resourceCode = "00011";
            if(rd && ss && sd) resourceCode = "00022";
            if(rd && ss && gr) resourceCode = "00033";
            if(wr && ind) resourceCode = "00100";
            if(wr && sd) resourceCode = "00200";
            if(wr && gr) resourceCode = "00300";
            if(ss && wr&& ind) resourceCode = "00101";
            if(ss && wr&&sd) resourceCode = "00202";
            if(ss && wr&&gr) resourceCode = "00303";
            if(wr && rd&&ind) resourceCode = "00110";
            if(wr && rd&&sd) resourceCode = "00220";
            if(wr && rd&&gr) resourceCode = "00330";
            if(wr && rd&&ss&&ind) resourceCode = "00111";
            if(wr && rd&&ss&&sd) resourceCode = "00222";
            if(wr && rd&&ss&&gr) resourceCode = "00333";
            if(sc &&ind) resourceCode = "01000";
            if(sc && sd) resourceCode = "02000";
            if(sc && gr) resourceCode = "03000";
            if(sc && ss && ind) resourceCode = "01001";
            if(sc && ss&&sd) resourceCode = "02002";
            if(sc &&ss&&gr) resourceCode = "03003";
            if(sc && ss&&ind) resourceCode = "01010";
            if(sc && rd&&sd) resourceCode = "02020";
            if(sc && rd&&gr) resourceCode = "03030";
            if(sc && rd&&ss&&ind) resourceCode = "01011";
            if(sc && rd&&ss&&sd) resourceCode = "02022";
            if(sc && rd&&ss&&gr) resourceCode = "03033";
            if(sc && wr&&ind) resourceCode = "01100";
            if(sc && wr&&sd) resourceCode = "02200";
            if(sc && wr&&gr) resourceCode = "03300";
            if(sc &&wr&&ss&&ind) resourceCode = "01101";
            if(sc &&wr&&ss&&sd) resourceCode = "02202";
            if(sc &&wr&&ss&&gr) resourceCode = "03303";
            if(sc &&wr&&rd&&ind) resourceCode = "01110";
            if(sc &&wr&&rd&&sd) resourceCode = "02220";
            if(sc &&wr&&rd&&gr) resourceCode = "03330";
            if(sc &&wr&&rd&&ss&&ind) resourceCode = "01111";
            if(sc &&wr&&rd&&ss&&sd) resourceCode = "02222";
            if(sc &&wr&&rd&&ss&&gr) resourceCode = "03333";
            if(ma &&ind) resourceCode = "10000";
            if(ma &&sd) resourceCode = "20000";
            if(ma &&gr) resourceCode = "30000";
            if(ma &&ss&&ind) resourceCode = "10001";
            if(ma &&ss&&sd) resourceCode = "20002";
            if(ma &&ss&&gr) resourceCode = "30003";
            if(ma &&rd&&ind) resourceCode = "10010";
            if(ma &&rd&&sd) resourceCode = "20020";
            if(ma &&rd&&gr) resourceCode = "30030";
            if(ma &&rd&&ss&&ind) resourceCode = "10011";
            if(ma &&rd&&ss&&sd) resourceCode = "20022";
            if(ma &&rd&&ss&&gr) resourceCode = "30033";
            if(ma &&wr&&ind) resourceCode = "10100";
            if(ma &&wr&&sd) resourceCode = "20200";
            if(ma &&wr&&gr) resourceCode = "30300";
            if(ma &&wr&&ss&&ind) resourceCode = "10101";
            if(ma &&wr&&ss&&sd) resourceCode = "20202";
            if(ma &&wr&&ss&&gr) resourceCode = "30303";
            if(ma &&wr&&rd&&ss&&ind) resourceCode = "10111";
            if(ma &&wr&&rd&&ss&&sd) resourceCode = "20222";
            if(ma &&wr&&rd&&ss&&gr) resourceCode = "30333";
            if(ma &&sc&&ind) resourceCode = "11000";
            if(ma &&sc&&sd) resourceCode = "22000";
            if(ma &&sc&&gr) resourceCode = "33000";
            if(ma &&sc&&ss&&ind) resourceCode = "11001";
            if(ma &&sc&&ss&&sd) resourceCode = "22002";
            if(ma &&sc&&ss&&gr) resourceCode = "33003";
            if(ma &&sc&&rd&&ind) resourceCode = "11010";
            if(ma &&sc&&rd&&sd) resourceCode = "22020";
            if(ma &&sc&&rd&&gr) resourceCode = "33030";
            if(ma &&sc&&rd&&ss&&ind) resourceCode = "11011";
            if(ma &&sc&&rd&&ss&&sd) resourceCode = "22022";
            if(ma &&sc&&rd&&ss&&gr) resourceCode = "33033";
            if(ma &&sc&&wr&&ind) resourceCode = "11100";
            if(ma &&sc&&wr&&sd) resourceCode = "22200";
            if(ma &&sc&&wr&&gr) resourceCode = "33300";
            if(ma &&sc&&wr&&ss&&ind) resourceCode = "11101";
            if(ma &&sc&&wr&&ss&&sd) resourceCode = "22202";
            if(ma &&sc&&wr&&ss&&gr) resourceCode = "33303";
            if(ma &&sc&&wr&&rd&&ind) resourceCode = "11110";
            if(ma &&sc&&wr&&rd&&sd) resourceCode = "22220";
            if(ma &&sc&&wr&&rd&&gr) resourceCode = "33330";
            if(ma &&sc&&wr&&rd&&ss&&ind) resourceCode = "11111";
            if(ma &&sc&&wr&&rd&&ss&&sd) resourceCode = "22222";
            if(ma &&sc&&wr&&rd&&ss&&gr) resourceCode = "33333";
            if(ss&&ot) resourceCode = "00005";
            if(rd&&ot) resourceCode = "00050";
            if(rd&&ss&&ot) resourceCode = "00055";
            if(wr&&ot) resourceCode = "00500";
            if(wr&&ss&&ot) resourceCode = "00505";
            if(rd&&rd&&ot) resourceCode = "00550";
            if(wr&&rd&&ss&&ot) resourceCode = "00555";
            if(sc&&ot) resourceCode = "05000";
            if(sc&&ss&&ot) resourceCode = "05005";
            if(sc&&rd&&ot) resourceCode = "05050";
            if(sc&&rd&&ss&&ot) resourceCode = "05055";
            if(sc&&wr&&ot) resourceCode = "05500";
            if(sc&&wr&&ss&&ot) resourceCode = "05505";
            if(sc&&wr&&rd&&ss&&ot) resourceCode = "05550";
            if(sc&&rd&&wr&&ss&&ot) resourceCode = "05555";
            if(ma&&ot) resourceCode = "50000";
            if(ma&&ss&&ot) resourceCode = "50005";
            if(ma&&rd&&ot) resourceCode = "50050";
            if(ma&&rd&&ss&&ot) resourceCode = "50055";
            if(ma&&wr&&ot) resourceCode = "50500";
            if(ma&&wr&&ss&&ot) resourceCode = "50505";
            if(ma&&rd&&rd&&ot) resourceCode = "50550";
            if(ma&&wr&&rd&&ss&&ot) resourceCode = "50555";
            if(ma&&sc&&ot) resourceCode = "55000";
            if(ma&&sc&&ss&&ot) resourceCode = "55005";
            if(ma&&sc&&rd&&ot) resourceCode = "55050";
            if(ma&&sc&&rd&&ss&&ot) resourceCode = "55055";
            if(ma&&sc&&wr&&ot) resourceCode = "55500";
            if(ma&&sc&&wr&&ss&&ot) resourceCode = "55505";
            if(ma&&sc&&wr&&rd&&ss&&ot) resourceCode = "55550";
            if(ma&&sc&&rd&&wr&&ss&&ot) resourceCode = "55555";
            if(noShow) resourceCode = "66666";
            if(ss&&ind&&g) resourceCode = "0000G";
            if(ss&&gr&&g) resourceCode = "0000H";
            if(ss&&ot&&g) resourceCode = "0000I";
            if(ss&&sd&&g) resourceCode = "0000J";
            if(rd&&ind&&g) resourceCode = "000G0";
            if(rd&&gr&&g) resourceCode = "000H0";
            if(rd&&ot&&g) resourceCode = "000I0";
            if(rd&&sd&&g) resourceCode = "000J0";
            if(rd&&ss&&ind&&g) resourceCode = "000GG";
            if(rd&&ss&&gr&&g) resourceCode = "000HH";
            if(rd&&ss&&ot&&g) resourceCode = "000II";
            if(rd&&ss&&sd&&g) resourceCode = "000JJ";
            if(wr&&ind&&g) resourceCode = "00G00";
            if(wr&&gr&&g) resourceCode = "00H00";
            if(wr&&ot&&g) resourceCode = "00I00";
            if(wr&&sd&&g) resourceCode = "00J00";
            if(wr&&ss&&ind&&g) resourceCode = "00G0G";
            if(wr&&ss&&gr&&g) resourceCode = "00H0H";
            if(wr&&ss&&ot&&g) resourceCode = "00I0I";
            if(wr&&ss&&sd&&g) resourceCode = "00J0J";
            if(wr&&rd&&ind&&g) resourceCode = "00GG0";
            if(wr&&rd&&gr&&g) resourceCode = "00HH0";
            if(wr&&rd&&ot&&g) resourceCode = "00II0";
            if(wr&&rd&&sd&&g) resourceCode = "00JJ0";
            if(wr&&rd&&ss&&ind&&g) resourceCode = "00GGG";
            if(wr&&rd&&ss&&gr&&g) resourceCode = "00HHH";
            if(wr&&rd&&ss&&ot&&g) resourceCode = "00III";
            if(wr&&rd&&ss&&sd&&g) resourceCode = "00JJJ";
            if(sc&&ind&&g) resourceCode = "0G000";
            if(sc&&gr&&g) resourceCode = "0H000";
            if(sc&&ot&&g) resourceCode = "0I000";
            if(sc&&sd&&g) resourceCode = "0J000";
            if(sc&&ss&&ind&&g) resourceCode = "0G00G";
            if(sc&&ss&&gr&&g) resourceCode = "0H00H";
            if(sc&&ss&&ot&&g) resourceCode = "0I00I";
            if(sc&&ss&&sd&&g) resourceCode = "0J00J";
            if(sc&&rd&&ind&&g) resourceCode = "0G0G0";
            if(sc&&rd&&gr&&g) resourceCode = "0H0H0";
            if(sc&&rd&&ot&&g) resourceCode = "0I0I0";
            if(sc&&rd&&sd&&g) resourceCode = "0J0J0";
            if(sc&&rd&&ss&&ind&&g) resourceCode = "0G0GG";
            if(sc&&rd&&ss&&gr&&g) resourceCode = "0H0HH";
            if(sc&&rd&&ss&&ot&&g) resourceCode = "0I0II";
            if(sc&&rd&&ss&&sd&&g) resourceCode = "0J0JJ";
            if(sc&&wr&&ind&&g) resourceCode = "0GG00";
            if(sc&&wr&&gr&&g) resourceCode = "0HH00";
            if(sc&&wr&&ot&&g) resourceCode = "0II00";
            if(sc&&wr&&sd&&g) resourceCode = "0JJ00";
            if(sc&&wr&&ss&&ind&&g) resourceCode = "0GG0G";
            if(sc&&wr&&ss&&gr&&g) resourceCode = "0HH0H";
            if(sc&&wr&&ss&&ot&&g) resourceCode = "0II0I";
            if(sc&&wr&&ss&&sd&&g) resourceCode = "0JJ0J";
            if(sc&&wr&&rd&&ind&&g) resourceCode = "0GGG0";
            if(sc&&wr&&rd&&gr&&g) resourceCode = "0HHH0";
            if(sc&&wr&&rd&&ot&&g) resourceCode = "0III0";
            if(sc&&wr&&rd&&sd&&g) resourceCode = "0JJJ0";
            if(sc&&wr&&rd&&ss&&ind&&g) resourceCode = "0GGGG";
            if(sc&&wr&&rd&&ss&&gr&&g) resourceCode = "0HHHH";
            if(sc&&wr&&rd&&ss&&ot&&g) resourceCode = "0IIII";
            if(sc&&wr&&rd&&ss&&sd&&g) resourceCode = "0JJJJ";
            if(ma&&sc&&ind&&g) resourceCode = "GG000";
            if(ma&&sc&&gr&&g) resourceCode = "HH000";
            if(ma&&sc&&ot&&g) resourceCode = "II000";
            if(ma&&sc&&sd&&g) resourceCode = "JJ000";
            if(ma&&ind&&g) resourceCode = "G0000";
            if(ma&&gr&&g) resourceCode = "H0000";
            if(ma&&ot&&g) resourceCode = "I0000";
            if(ma&&sd&&g) resourceCode = "J0000";
            if(ma&&ss&&ind&&g) resourceCode = "G000G";
            if(ma&&ss&&gr&&g) resourceCode = "H000H";
            if(ma&&ss&&ot&&g) resourceCode = "I000I";
            if(ma&&ss&&sd&&g) resourceCode = "J000J";
            if(ma&&rd&&ss&&ind&&g) resourceCode = "G00GG";
            if(ma&&rd&&ss&&gr&&g) resourceCode = "H00HH";
            if(ma&&rd&&ss&&ot&&g) resourceCode = "I00II";
            if(ma&&rd&&ss&&sd&&g) resourceCode = "J00JJ";
            if(ma&&wr&&ind&&g) resourceCode = "G0G00";
            if(ma&&wr&&gr&&g) resourceCode = "H0H00";
            if(ma&&wr&&ot&&g) resourceCode = "I0I00";
            if(ma&&wr&&sd&&g) resourceCode = "J0J00";
            if(ma&&wr&&ss&&ind&&g) resourceCode = "G0G0G";
            if(ma&&wr&&ss&&gr&&g) resourceCode = "H0H0H";
            if(ma&&wr&&ss&&ot&&g) resourceCode = "I0I0I";
            if(ma&&wr&&ss&&sd&&g) resourceCode = "J0J0J";
            if(ma&&wr&&rd&&ss&&ind&&g) resourceCode = "G0GGG";
            if(ma&&wr&&rd&&ss&&gr&&g) resourceCode = "H0HHH";
            if(ma&&wr&&rd&&ss&&ot&&g) resourceCode = "I0III";
            if(ma&&wr&&rd&&ss&&sd&&g) resourceCode = "J0JJJ";
            if(ma&&sc&&ss&&ind&&g) resourceCode = "GG00G";
            if(ma&&sc&&ss&&gr&&g) resourceCode = "HH00H";
            if(ma&&sc&&ss&&ot&&g) resourceCode = "II00I";
            if(ma&&sc&&ss&&sd&&g) resourceCode = "JJ00J";
            if(ma&&sc&&rd&&ind&&g) resourceCode = "GG0G0";
            if(ma&&sc&&rd&&gr&&g) resourceCode = "HH0H0";
            if(ma&&rd&&ot&&g) resourceCode = "II0I0";
            if(ma&&sc&&rd&&sd&&g) resourceCode = "JJ0J0";
            if(ma&&sc&&wr&&ss&&ind&&g) resourceCode = "GGG0G";
            if(ma&&sc&&wr&&ss&&gr&&g) resourceCode = "HHH0H";
            if(ma&&sc&&wr&&ss&&ot&&g) resourceCode = "III0I";
            if(ma&&sc&&wr&&ss&&sd&&g) resourceCode = "JJJ0J";
            if(ma&&sc&&wr&&ind&&g) resourceCode = "GGG00";
            if(ma&&sc&&wr&&gr&&g) resourceCode = "HHH00";
            if(ma&&sc&&wr&&ot&&g) resourceCode = "III00";
            if(ma&&sc&&wr&&sd&&g) resourceCode = "JJJ00";
            if(ma&&sc&&wr&&ss&&ind&&g) resourceCode = "GGG0G";
            if(ma&&sc&&wr&&ss&&gr&&g) resourceCode = "HHH0H";
            if(ma&&sc&&wr&&ss&&ot&&g) resourceCode = "III0I";
            if(ma&&sc&&wr&&ss&&sd&&g) resourceCode = "JJJ0J";
            if(ma&&sc&&wr&&rd&&ind&&g) resourceCode = "GGGG0";
            if(ma&&sc&&wr&&rd&&gr&&g) resourceCode = "HHHH0";
            if(ma&&sc&&wr&&rd&&ot&&g) resourceCode = "IIII0";
            if(ma&&sc&&wr&&rd&&sd&&g) resourceCode = "JJJJ0";
            if(ma&&sc&&wr&&rd&&ss&&ind&&g) resourceCode = "GGGGG";
            if(ma&&sc&&wr&&rd&&ss&&gr&&g) resourceCode = "HHHHH";
            if(ma&&sc&&wr&&rd&&ss&&ot&&g) resourceCode = "IIIII";
            if(ma&&sc&&wr&&rd&&ss&&sd&&g) resourceCode = "JJJJJ";
            if(wr && ww) resourceCode = "00800";
            if(rd && ww) resourceCode = "00080";
            if(ss && ww) resourceCode = "00008";
            if(wr&&rd && ww) resourceCode = "00808";
            if(rd&&ss && ww) resourceCode = "00088";
            if(wr&&rd && ww) resourceCode = "00080";
            if(wr&&rd&&ss && ww) resourceCode = "00888";


        System.out.println(studentId
                + ","
                + date + ","
                + timeIn[indexForTimeInOut] + ","
                + timeOut[indexForTimeInOut] + ","
                + courseNumber + ","
                + resourceCode);
        jButton2.setText(studentId
                + "  "
                + date + "  "
                + timeIn[indexForTimeInOut] + "  "
                + timeOut[indexForTimeInOut] + "  "
                + courseNumber + "  "
                + resourceCode);
            fbw.write(studentId
                + ","
                + date + ","
                + timeIn[indexForTimeInOut] + ","
                + timeOut[indexForTimeInOut] + ","
                + courseNumber + ","
                + resourceCode);
            fbw.newLine();
            fbw.close();
            jCheckBox1.setSelected(false);
            jCheckBox2.setSelected(false);
            jCheckBox3.setSelected(false);
            jCheckBox4.setSelected(false);
            jCheckBox5.setSelected(false);
            jCheckBox6.setSelected(false);
            jCheckBox7.setSelected(false);
            jCheckBox8.setSelected(false);
            jCheckBox9.setSelected(false);
            jCheckBox10.setSelected(false);
            jCheckBox11.setSelected(false);
            jCheckBox12.setSelected(false);
            jTextField1.setText("");
            jTextField1.setCursor(new Cursor(Cursor.MOVE_CURSOR)); 
            jTextField2.setText("");
            jTextField3.setText("");
        }catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed

    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed

    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void jCheckBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox9ActionPerformed

    private void jCheckBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox10ActionPerformed

    private void jCheckBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox11ActionPerformed

    private void jCheckBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox12ActionPerformed

    private void jCheckBox2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCheckBox2KeyPressed
    }//GEN-LAST:event_jCheckBox2KeyPressed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
       
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;


                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LacSessionRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LacSessionRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LacSessionRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LacSessionRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {

                new LacSessionRecords().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
